# Site settings
title: wvn
email: samuel[punkt]mnet[at]gmail[punkt]com 
description: "Veranlassen statt nachlassen"
baseurl: /wvn
url: "http://samnet.github.io/wvn"

# Build settings
markdown: kramdown
permalink: pretty
