# Site settings
title: wvl
email: samuel[punkt]mnet[at]gmail[punkt]com 
description: "Veranlassen statt nachlassen"
baseurl: /wvl
url: "http://samnet.github.io/connaissance"

# Build settings
markdown: kramdown
permalink: pretty
